version: '2'
services:
  api:
    container_name: teklifyap-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PASSWORD
      - USERNAME
      - URI
      - SMTP_PASSWORD
      - BASE_URL
    volumes:
      - storage_dev:/app/storage
    ports:
      - "8080:8080"

volumes:
  storage_dev: