version: '2'
services:
  api:
    container_name: teklifyap-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - storage_dev:/app/storage
    ports:
      - "8080:8080"

volumes:
  storage_dev: